---
- name: Prepare
  hosts: all
  tasks:
    - name: Refresh apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install git
      package:
        name: git

    - name: Install packages for RHEL
      package:
        name:
          - iproute
          - NetworkManager
      when: ansible_os_family == "RedHat"

    - name: Start NetworkManager
      service:
        name: NetworkManager
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Install packages for Debian
      package:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - iproute2
      when: ansible_os_family == "Debian"

    #- name: Enable IPv4
    #  command: sysctl -w net.ipv4.conf.all.disable_ipv4=0
    #  when: ansible_os_family == "Debian"

    #- name: Disable IPv6
    #  command: sysctl -w net.ipv6.conf.all.disable_ipv6=1
    #  when: ansible_os_family == "Debian"
