---
- name: Prepare
  hosts: all
  tasks:
    - name: Refresh apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install git
      package:
        name: git

    - name: Install packages for Debian
      package:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
      when: ansible_os_family == "Debian"

    - name: Enable IPv4
      command: sysctl -w net.ipv6.conf.all.disable_ipv4=0

    - name: Disable IPv6
      command: sysctl -w net.ipv6.conf.all.disable_ipv6=1
