---
- name: Prepare
  hosts: all
  tasks:
    - name: Refresh apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Install git
      package:
        name: git
    - name: Install packages for Debian
      package:
        name:
          - gpg
          - gpg-agent
          - procps
          - curl
          - dbus
      when: ansible_os_family == "Debian"
    - name: Start DBus service
      shell: /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only &
      changed_when: false
      when: ansible_os_family == "Debian"
